#!/bin/bash

sudo apt-get update
sudo apt-get install python3
sudo apt-get install python3-pip
sudo apt-get install python3-venv

sudo python3 -m pip install --upgrade pip
sudo pip install virtualenv
sudo python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt